web: DJANGO_SETTINGS_MODULE=config.settings.production daphne -b 0.0.0.0 -p $PORT config.asgi:application
release: DJANGO_SETTINGS_MODULE=config.settings.production python manage.py migrate --noinput && DJANGO_SETTINGS_MODULE=config.settings.production python manage.py collectstatic --noinput
