[build]
builder = "nixpacks"

[deploy]
releaseCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput"
startCommand = "daphne -b 0.0.0.0 -p $PORT config.asgi:application"
healthcheckPath = "/health/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
