# Generated by Django 5.0.6 on 2026-04-16 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breaking_news', models.BooleanField(default=True)),
                ('top_stories', models.BooleanField(default=True)),
                ('local_news', models.BooleanField(default=True)),
                ('health', models.BooleanField(default=False)),
                ('sports', models.BooleanField(default=False)),
                ('business', models.BooleanField(default=False)),
                ('entertainment', models.BooleanField(default=False)),
                ('politics', models.BooleanField(default=False)),
                ('science', models.BooleanField(default=False)),
                ('environment', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alert_preferences',
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'push_tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
