# Generated by Django 5.1.5 on 2026-07-24 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRepost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(choices=[('uploaded', 'Uploaded'), ('external', 'External')], max_length=16)),
                ('video_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_reposts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'video_reposts',
                'constraints': [models.UniqueConstraint(fields=('user', 'video_type', 'video_id'), name='unique_user_video_repost')],
            },
        ),
    ]
