# Generated by Django 5.0.6 on 2026-04-16 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('BUSINESS', 'Business'), ('HEALTH', 'Health'), ('WORLD', 'World'), ('POLITICS', 'Politics'), ('TECHNOLOGY', 'Technology'), ('SPORTS', 'Sports'), ('ARTS', 'Arts'), ('SCIENCE', 'Science'), ('INDIGENOUS', 'Indigenous'), ('ENVIRONMENT', 'Environment'), ('OPINION', 'Opinion'), ('ENTERTAINMENT', 'Entertainment')], default='GENERAL', max_length=32)),
                ('img_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('headline', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('BUSINESS', 'Business'), ('HEALTH', 'Health'), ('WORLD', 'World'), ('POLITICS', 'Politics'), ('TECHNOLOGY', 'Technology'), ('SPORTS', 'Sports'), ('ARTS', 'Arts'), ('SCIENCE', 'Science'), ('INDIGENOUS', 'Indigenous'), ('ENVIRONMENT', 'Environment'), ('OPINION', 'Opinion'), ('ENTERTAINMENT', 'Entertainment')], default='GENERAL', max_length=32)),
                ('img_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField()),
                ('is_live', models.BooleanField(default=False)),
                ('is_updated', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('RSS', 'RSS'), ('USER', 'User')], default='RSS', max_length=8)),
                ('feed_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regions', models.ManyToManyField(blank=True, related_name='articles', to='regions.region')),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['category', '-published_at'], name='articles_categor_75eb38_idx'), models.Index(fields=['feed_key', '-published_at'], name='articles_feed_ke_8def85_idx'), models.Index(fields=['source', '-published_at'], name='articles_source_d91500_idx')],
            },
        ),
    ]
