# Generated by Django 5.0.6 on 2026-04-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('POLITICS', 'Politics'), ('BUSINESS', 'Business'), ('WORLD', 'World'), ('ENVIRONMENT', 'Environment'), ('SCIENCE', 'Science'), ('INDIGENOUS', 'Indigenous'), ('OPINION', 'Opinion'), ('JOBS_CAREERS', 'Jobs & Careers'), ('SCHOLARSHIPS', 'Scholarships'), ('GRANTS', 'Grants'), ('IMMIGRATION', 'Immigration'), ('REAL_ESTATE', 'Real Estate'), ('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('TECHNOLOGY', 'Technology'), ('TRAVEL', 'Travel'), ('FOOD', 'Food'), ('EVENTS', 'Events'), ('GOVERNMENT', 'Government'), ('SPORTS', 'Sports'), ('ENTERTAINMENT', 'Entertainment'), ('ARTS', 'Arts'), ('MUSIC', 'Music')], default='GENERAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('POLITICS', 'Politics'), ('BUSINESS', 'Business'), ('WORLD', 'World'), ('ENVIRONMENT', 'Environment'), ('SCIENCE', 'Science'), ('INDIGENOUS', 'Indigenous'), ('OPINION', 'Opinion'), ('JOBS_CAREERS', 'Jobs & Careers'), ('SCHOLARSHIPS', 'Scholarships'), ('GRANTS', 'Grants'), ('IMMIGRATION', 'Immigration'), ('REAL_ESTATE', 'Real Estate'), ('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('TECHNOLOGY', 'Technology'), ('TRAVEL', 'Travel'), ('FOOD', 'Food'), ('EVENTS', 'Events'), ('GOVERNMENT', 'Government'), ('SPORTS', 'Sports'), ('ENTERTAINMENT', 'Entertainment'), ('ARTS', 'Arts'), ('MUSIC', 'Music')], default='GENERAL', max_length=32),
        ),
    ]
