# Generated by Django 5.0.6 on 2026-04-20 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remap_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(help_text='Upload a local MP4, MOV, M4V, or WebM file from Django admin.', upload_to='news_videos/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'm4v', 'webm'])])),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional thumbnail image. If omitted, the app will show a placeholder card.', upload_to='news_videos/thumbnails/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'news_videos',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('BUSINESS', 'Business'), ('HEALTH', 'Health'), ('ENTERTAINMENT', 'Entertainment'), ('TECHNOLOGY', 'Technology'), ('SPORTS', 'Sports'), ('IMMIGRATION', 'Immigration'), ('AVIATION', 'Aviation'), ('INDIGENOUS', 'Indigenous'), ('POLITICS', 'Politics'), ('EVENTS', 'Events'), ('AUTO_NEWS', 'Auto News'), ('BLACKS_IN_CANADA', 'Blacks in Canada'), ('EDUCATION', 'Education in Canada'), ('OPPORTUNITIES', 'Opportunities'), ('WORLD', 'World')], default='GENERAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('BUSINESS', 'Business'), ('HEALTH', 'Health'), ('ENTERTAINMENT', 'Entertainment'), ('TECHNOLOGY', 'Technology'), ('SPORTS', 'Sports'), ('IMMIGRATION', 'Immigration'), ('AVIATION', 'Aviation'), ('INDIGENOUS', 'Indigenous'), ('POLITICS', 'Politics'), ('EVENTS', 'Events'), ('AUTO_NEWS', 'Auto News'), ('BLACKS_IN_CANADA', 'Blacks in Canada'), ('EDUCATION', 'Education in Canada'), ('OPPORTUNITIES', 'Opportunities'), ('WORLD', 'World')], default='GENERAL', max_length=32),
        ),
    ]
