# Generated by Django 5.2.16 on 2026-07-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_expand_externalvideo_urls'),
        ('regions', '0004_fix_victoria_rss_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='user_posts', to='regions.region'),
        ),
    ]
