# Generated by Django 5.0.6 on 2026-04-16 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('province', models.CharField(max_length=120)),
                ('rss_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'regions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_regions', to='regions.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_regions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_regions',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='userregion',
            constraint=models.UniqueConstraint(fields=('user', 'region'), name='unique_user_region'),
        ),
    ]
